### ISSUE TITLE
[GenerativeToken] projects sometimes disappear from feed due to pagination inconsistencies

### ISSUE THREAD

**Issue by louisholley** [fxhash/fxhash-api#36]
bit of a tricky one to explain, but I think this happens when multiple tokens opening at the same time for minting lie on pagination boundaries. for a contrived example:

these three projects all open at the same time:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4563781/215776398-2d994547-f6a7-49f9-9b60-b0a046ed08b8.png">

if we do `take: 2`, we see the first two returned (albeit in a different order):
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/4563781/215776468-95cc9831-d97b-4523-b12e-53a70e52a325.png">

if we then bump the `skip` by 2, we see that we get a repeat of one of the tokens in the last page, and we miss the `Echoes of Enough` token:
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/4563781/215776519-6a8a6d9b-c95e-434f-a846-1d2ac6060ee9.png">

while this is a contrived example, it's happening with the queries our frontend is making (pages of `size=20` and skipping multiples of 20 thereafter). need to dig in to the pagination logic as I feel that this shouldn't be happening at the db level - if it is maybe there's a secondary search we can do (e.g. order by opens at and then by ID) so that we don't see these non-deterministic results in the feed

**Comment by GemN** [comment]
I think it's the classic problem of skip/take. Anything with a feed will eventually skip or duplicate items since any new real time addition to a query will modify the underlaying order.
The solution for this is *simple* (as it's a common problem, not simple to implement haha): a cursor based pagination.
No matter how much the order will be modify, the next or previous items will always be the same.

We mentioned a while ago in discord - that would require some deep refacto but we'll eventually have to do it

**Comment by louisholley** [comment]
@GemN I think the problem actually runs deeper than that though - the items are returned non-deterministically based on which value you provide for `take`...so at least in the short term, if we manage to resolve that, we won't have projects missing from incoming
